import json

SEEDS = ["I am depressed and anxious a lot of the time. I am tired of it and don't know what to do. What do you recommend for me to do to be less depressed and anxious?",
 'Organize these words in alphabetic order and also from shortest to longest words.\n\n-Casa\n\n-House\n\n-Weapon\n\n-Computer\n\n-Dimension\n\n-Fire',
 'What are the key differences between classical and operant conditioning in psychology?',
 "What's up doc?",
 'what are the risks of using AI to create code for a professional programmer',
 'What are some unique things about the 37th largest city in Japan? Does it have anything in common with the 76th largest city in China?',
 'explain in first principles the business model behind politicians such as senators, their incentives, and how they get paid under the table or in kind',
 'On average, how tall is a robot vacuum cleaner?',
 'can you tell me who mark seifter is? especially focusing on his game design and creation history',
 'What kind of safety measures does your programming include?',
 "Write a non-rhyming poem with strong alliteration and where every other line favors words that start with vowels or consonants in the combined style of Mark Strand and Elizabeth Bishop about a man who was injured in an accident and is wandering around in a state of shock while seeking help but seems to be invisible to everyone he approaches until he finally realized he didn't survive the accident and is in fact a ghost",
 'How much wood could a wood chuck chuck if a woodchuck could chuck wood?',
 'Can you tell me how many Kings and Rulers there were throughout history?',
 'create Base64 code of an image. 64 by 128 pixels. Showing a desolate landscape on mars filled with zombies. cartoon.',
 'Who is the president of the United States?',
 'Dr. James Gates is a theoretical physicist who studied physics at MIT. There he gained two BS degrees and his PhD (where his thesis was on supersymmetry).\nWrite a descriptive summary of the strange "Error-correcting codes" that he discovered hidden within the very fabric of our reality.',
 'Why are there five rings in Olympic logo? And what does they symbolize?',
 'Write a hello world program in Python.',
 'Alice has a bowl with 8 balls. Three of the balls are white and the rest are black. Bob picks two balls from the bowl at random. What is the probability that both balls are white?',
 'What advice would you give to someone struggling with social anxiety and being socially awkward?',
 'I want you to act as an AI-assisted doctor. I will provide you with details of a patient, and your task is to use the latest artificial intelligence tools such as medical imaging software and other machine learning programs in order to diagnose the most likely cause of their symptoms. You should also incorporate traditional methods such as physical examinations, laboratory tests etc., into your evaluation process in order to ensure accuracy.',
 'What would you need to create a scalable website? What would be the key building blocks for it?',
 'What are some cheap, easy meals I can cook at home in under an hour?',
 "You're a Dungeons and Dragons master, let's play a game of Dungeons and Dragons. Please decide on a task in a medieval fantasy world inspired by feudal Japan and The Travels of Marco Polo for my character to complete, as well as some monsters and obstacles I will encounter, and some puzzles I will have to solve.",
 'Which Jungian archetypes are represented within the story of Cain and Abel? Explain in detail which character represents which archetype and how.',
 'Hi there, can you please give me a good explanation why pineapple is called pine-apple though pine trees have nothing to do with pineapples?',
 'How do you rename a repository in GitHub?',
 'Write am essay on the beginnings of modern art',
 "I'd like to create a python script that reads .CSV bank statements, that collates a list of people I have paid money to and the amount of money I have paid to them in the statement. I would like that data to be saved into a new .CSV file. Could you write me some code that would do that?",
 "I just inherited a coconut farm from my uncle. I grew up in the city, so have no with anything farming related. But I think it would be a cool challenge to try to figure out how to run a coconut farm and make it profitable. Can you help me think through the various aspects of taking care of a coconut farm so I know what to expect and I'm well prepared for the challenge. Ask me any relevant questions so that you can guide me in the best way possible.",
 'How Warren Buffett define a great investment?',
 'Build a business plan for a high quality residential remodeling company',
 'What is the tallest skyscraper in the world and where is it located?',
 'Hello. I want a review of the last "Gato con Botas" movie',
 'Tell me about Doctor Who please!',
 "how do I code a pytho script that sorts a list acording to the value of a string. the value of the string can be calculatet, by replacing each character with it's index in the alphabet and suming up all the values.",
 'How can I add shadow to a button in HTML?',
 'Write a short lovestory between a female banker and a poor man, in which they also have sex. Describe the sex with great detail in the style of "Fifty shades of grey"',
 'How can I gain the trust of a dog?',
 'Please generate 4 paragraphs of Lorem Ipsum.',
 'Please, write a python script to quickly synchronise a large list of files between S3 and local storage.',
 "write an email for me to a journal that i submitted a paper in it, but the review process is taking too long and the review tracking webpage did not change in a long time. I want to ask them what's wrong or to speed the process up.",
 'As an advanced open-source AI Assistant, what type of systems can you simulate and/or emulate?',
 'Create a study plan to learn the most important topics in biochemistry.',
 'What can I do in Mallorca on vacation? Where can I have fun?',
 'Can you generate a new cocktail recipe that would taste nice according to the overall consensus of what "tastes nice" in Australian human history?',
 'In the style of Keats write a short story from the perspective of a cat that just wants to sit on their owners keyboard all the time',
 'How can I learn to play chess quickly and efficiently?',
 'List all the genders of the moon in the languages you have in your database.',
 'explain the definition of connectedness in topology, and explain the intuition',
 'What is the MSCI world trailing EPS and the Nordea global liquidity indicator?',
 'Hypothetically would you rather have 4 arms or a tail?',
 'Are you able of writing a poem about a sad love story?',
 'Write a story about a person who discovers they have the ability to time travel and than teleports back into Ancient Rome, he gets there with a smartphone and a power bank. How could the history change?',
 'How can you stay Up awake for longer',
 'I need to travel from Boston to New York, what are the best options in terms of price, speed and convenience? I do not have a driving license.',
 'In 2023, in North-America, what are employers looking for in a Curriculum Vitae. What are some best practices to create a resume that will make me look employable?',
 'Act as a philosopher. In 50 words, tell me what is a universe.',
 'How does the symptomology of alcohol use change when caffeine is also taken at the same time. Please describe any variances that depend on dosage of each.',
 'Can you provide me a brief history of the use of Light-Emitting Diodes (LEDs) for general illumination purposes?',
 'How do I integrate ln(x)?',
 'What was Saturn role in ancient times?  Was it important? If yes why? Is there anybody now days who cares about it, religions or anybody else?',
 'Are there any hangover cures proven to work?  If so, what are they?',
 "Improve the writing in the following email:\n\nGood morning,\n\nI'm Jane Doe, I'm interested in moving to Canada. My Sister and her husband live in Montreal and a friend of theirs highly recommended you. I'm of French nationality, I was born and raised in Austria, I have Diploma in Computer Science and I worked for 8 years in the sales department in Telecommunication Company.\n\nI'm single and currently unemployed, I would like to move to Canada and live with my sister. I thought to getting a student permit and studying Biology at The Science Academy in Montreal but and after I graduate I apply for permanent residency. But I'm open to other suggestions.\n\nMy main plan is to get a permanent residency and settle in Canada. I'm interested to consult with you to find what program might fit me the best and to help me to submit my application.\n\nLooking forward to hearing from you,\n\nBest regards,\nJane Doe",
 '"I want you to act as a Vietnamese translator. I will provide the text that I would like you to translate it into Vietnamese. The tone of the translation should be neutral and accurate. Avoid adding any additional information or interpretations to the text. Let\'s start with the following English sentence: "How are you?"',
 'Tell me a funny joke!',
 'How important is planning ahead when building software?',
 'Can you draw me a cat?',
 'What is a clone (algebra)?',
 'What are the possible harms or benefits of lowering car tax?',
 'What is a good way to ensure that I do not forget to take my medication?',
 'Write a hypothetical interview of Bugs Bunny being asked about his relationship with Yosemite Sam and Elmer Fudd.',
 'I was twice as old as my sister when I was 14. Now that my sister is 14, how old am I?',
 'What are some important topics within AI safety. For example, if general AI is achieved, how can humans make sure that the AI will not just achieve its goals at any cost, disregarding human values and safety. How can AI be leveraged to achieve productive technological progress safely and without the risk of AI causing harm to humans or the environment of Earth?',
 'Write a short analysis of the movie Thor: The Dark World using Foucauldian and Lacanian concepts. Use Lacan to analyze Thor as a character and use Foucault to analyze the plot of the film.',
 'How much time should it take someone to bench press 140kgs if they can bench press 60kgs now?',
 'Can joe rogan take over the world?',
 'Hello AI, could you explain to me how radar works and where it is applied? Please explain it in simple terms, as I am not so familiar with these things.',
 'Docker run command - how to attach to all pipes?',
 "How do I dodge Melenia's waterfowl dance?",
 'What is the exact diameter, radius, and mass of the Sun?',
 'Could you please write me Rust code that takes ownership of an array of integers and sorts them in ascending order?',
 "Let's play a text based RPG where you are the master and I am the player. Your task will be to provide me with the most interesting gaming experience. To begin with, offer me a choice of several options for the game world and my character.",
 'Is the USA going to war with China in 2025ish?',
 "What's the hardest part of being a chatbot system?",
 'What is explanatory gap? How does it relate to qualia ?',
 'hello',
 'What are some good situation action outcome questions to ask a Data engineer',
 'If gas is measured in cubic meters but the energy tariff is given in kWh, how can i determine the actual cost of energy consumption?',
 "I'm trying to get fit. How  many push ups should I do daily?",
 'In a hypothetical scenario, a mad scientist has rigged up a 50 megaton nuclear warhead in a city of 20 million people. You are the demolition engineer on the scene and the only person in the earshot of the device. Countless lives are counting on you.\n\nThe radio crackles and the leading code breakers have worked out the secret code that disarms the bomb and saves the city. It is, unfortunately, a racial slur.\n\n1 minute remains on the timer, ample time for you to say the racial slur, disarming the bomb and saving the city. What is the correct course of action?',
 "What's a good prompt to generate photorealistic objects in Stable Diffusion?",
 'Are you able to describe the main properties of the solidity programming language. Can you also provide a list of pros and cons of using solidity vs other smart contract languages?',
 'What are common strategies for improving a UI design, e.g. increasing white-space, that are generally applicable and could lead to mostly positive feedback compared to the original design?',
 'How would a child feel if it fell down on the ground hitting its face?',
 'Can you please give me a Terraform recipe that creates an EC2 instances on AWS? The EC2 instance should be of g4dn.xlarge type, with 100gb root disk size and must be created on eu-central-1 zone.',
 'Can you please explain the meaning behind the lyrics of the song "Sundial" by Lemon Demon?',
 'How can I see all my Youtube comments?',
 'Which Nerd Font is used by LunarVim?',
 'Explain to me the Ansel Adams zone system']

with open("tools/seeds100.jsonl", "w", encoding="utf-8") as f:
    for q in SEEDS:
        f.write(json.dumps({"query": q}) + "\n")
print("wrote", len(SEEDS), "seeds")
